language: python
python:
  - "3.6"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install .
script:
  - pytest --cov bignmf
after_success:
  - coveralls